version: "3.8"

networks:
  mynetwork:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - "8000"
    networks:
      - mynetwork

  nginx1:
    image: my-nginx-image:latest
    volumes:
      - ./nginx/default1.conf:/etc/nginx/conf.d/default.conf
      - ./backend/staticfiles:/app/staticfiles
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - mynetwork

  nginx2:
    image: my-nginx-image:latest
    volumes:
      - ./nginx/default1.conf:/etc/nginx/conf.d/default.conf
      - ./backend/staticfiles:/app/staticfiles
    depends_on:
      - backend
    expose:
      - "80"
    networks:
      - mynetwork

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
    depends_on:
      - nginx1
      - nginx2
    networks:
      - mynetwork
